# Generated by Django 5.2.4 on 2025-08-05 21:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('usuario_base', 'Usuario Base')], default='usuario_base', max_length=20),
        ),
        migrations.AlterField(
            model_name='acta',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='actas/', validators=[api.models.validate_file_extension, api.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='gestiones/', validators=[api.models.validate_file_extension, api.models.validate_file_size]),
        ),
    ]
