# Generated by Django 5.2.4 on 2025-08-05 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_rol_alter_acta_pdf_alter_gestion_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
