# Generated by Django 5.2.4 on 2025-08-06 02:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_acta_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromiso',
            name='responsable',
            field=models.CharField(max_length=100, validators=[api.models.validate_responsable]),
        ),
    ]
